Repository scylladb/local-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#30 Pin GH Action installing Kubernetes to newest tag
  .github/actions/run-e2e/action.yaml
Labels: kind/machinery, priority/important-soon, size/XS

#33 Make sure xfs-disk-setup lands on the same nodes as local-csi-driver
  example/disk-setup/50_daemonset.yaml
Labels: kind/cleanup, priority/important-soon, size/XS

#35 Make xfs-disk-setup DaemonSet reentrant
  example/disk-setup/50_daemonset.yaml
Labels: kind/cleanup, priority/important-soon, size/XS

#37 Fix e2e to use in-cluster config
  go.mod
  pkg/cmd/tests/options.go
Labels: kind/cleanup, priority/important-soon, size/S

#38 Add OWNERS
  OWNERS
Labels: kind/machinery, priority/important-soon, size/S

#41 Update dependencies
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/test_suite.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/v2/reporters/json_report.go
  vendor/github.com/onsi/ginkgo/v2/types/code_location.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/version.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/modules.txt
Labels: kind/feature, priority/important-longterm, area/dependency, lgtm, size/XL, approved
