Repository scylladb/local-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#65 Switch runtime image to UBI
  images/local-csi-driver/Dockerfile
Labels: kind/machinery, priority/important-soon, size/XS, lgtm, approved

#66 Add zimnx as required dependency reviewer
  OWNERS
Labels: kind/cleanup, priority/important-longterm, size/XS, lgtm, approved

#68 Change image base image to UBI 9.5 minimal
  images/local-csi-driver-tests/Dockerfile
  images/local-csi-driver/Dockerfile
Labels: kind/feature, priority/important-soon, size/XS, lgtm, approved

#67 Bump Go to 1.23
  go.mod
  images/local-csi-driver-tests/Dockerfile
Labels: kind/feature, priority/important-soon, area/dependency, size/XS, lgtm, approved
