Repository scylladb/local-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#53 Fix NodePublishVolume and ValidateVolumeCapabilities debug logs
  pkg/driver/controller.go
  pkg/driver/node.go
Labels: kind/feature, priority/important-longterm, size/XS, lgtm, approved

#56 Rename k8s-local-volume-provisioner to local-csi-driver
  .github/workflows/releases.yaml
  Makefile
  README.md
  cmd/local-csi-driver-tests/local-csi-driver-tests.go
  cmd/local-csi-driver/local-csi-driver.go
  deploy/kubernetes/local-csi-driver/50_daemonset.yaml
  example/disk-setup/50_daemonset.yaml
  go.mod
  hack/ci-deploy.sh
  images/local-csi-driver-tests/Dockerfile
  images/local-csi-driver/Dockerfile
  pkg/cmd/local-csi-driver/driver.go
  pkg/cmd/tests/tests.go
  pkg/cmd/tests/tests_run.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/limit/xfs/limit.go
  pkg/driver/node.go
  pkg/driver/volume/volumemanager.go
  pkg/util/slices/slices_test.go
  test/e2e/include.go
  test/e2e/set/localdriver/capacity.go
  test/e2e/set/localdriver/upstream.go
  test/sanity/set/localdriver/sanity_test.go
Labels: area/dependency, size/L, lgtm, approved

#58 [v0.4] Rename k8s-local-volume-provisioner to local-csi-driver
  .github/workflows/releases.yaml
  Makefile
  README.md
  cmd/local-csi-driver-tests/local-csi-driver-tests.go
  cmd/local-csi-driver/local-csi-driver.go
  deploy/kubernetes/local-csi-driver/50_daemonset.yaml
  example/disk-setup/50_daemonset.yaml
  go.mod
  hack/ci-deploy.sh
  images/local-csi-driver-tests/Dockerfile
  images/local-csi-driver/Dockerfile
  pkg/cmd/local-csi-driver/driver.go
  pkg/cmd/tests/tests.go
  pkg/cmd/tests/tests_run.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/limit/xfs/limit.go
  pkg/driver/node.go
  pkg/driver/volume/volumemanager.go
  pkg/util/slices/slices_test.go
  test/e2e/include.go
  test/e2e/set/localdriver/capacity.go
  test/e2e/set/localdriver/upstream.go
  test/sanity/set/localdriver/sanity_test.go
Labels: kind/cleanup, priority/critical-urgent, area/dependency, size/L, lgtm, approved

#62 Update dependencies
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, area/dependency, size/L, lgtm, approved

#63 [v0.4] Update dependencies
  go.mod
  go.sum
  vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/defaultfs.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_unix.go
  vendor/k8s.io/kubernetes/pkg/util/filesystem/util_windows.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, area/dependency, size/L, lgtm, approved
