Repository scylladb/local-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#86 [v0.4] Bump Kubernetes dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/cli-runtime/pkg/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/printers/name.go
  vendor/k8s.io/cli-runtime/pkg/printers/template.go
  vendor/k8s.io/cli-runtime/pkg/printers/yaml.go
  vendor/k8s.io/cli-runtime/pkg/resource/builder.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubectl/pkg/cmd/attach/attach.go
  vendor/k8s.io/kubectl/pkg/cmd/create/create_service.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go
  vendor/k8s.io/kubectl/pkg/cmd/diff/diff.go
  vendor/k8s.io/kubectl/pkg/cmd/drain/drain.go
  vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go
  vendor/k8s.io/kubectl/pkg/cmd/get/customcolumn.go
  vendor/k8s.io/kubectl/pkg/cmd/get/get.go
  vendor/k8s.io/kubectl/pkg/cmd/portforward/portforward.go
  vendor/k8s.io/kubectl/pkg/cmd/taint/taint.go
  vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go
  vendor/k8s.io/kubectl/pkg/util/templates/help_flags_printer.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go
  vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volumelimits.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/modules.txt
Labels: kind/feature, priority/important-soon, area/dependency, lgtm, size/XL, approved

#88 Bump deps and builder to `golang-1.24`
  go.mod
  go.sum
  images/local-csi-driver-tests/Dockerfile
  images/local-csi-driver/Dockerfile
  vendor/cel.dev/expr/README.md
  vendor/github.com/go-openapi/jsonpointer/.golangci.yml
  vendor/github.com/go-openapi/jsonpointer/errors.go
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/errors.go
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/yaml.go
  vendor/github.com/google/cel-go/cel/env.go
  vendor/github.com/google/cel-go/cel/inlining.go
  vendor/github.com/google/cel-go/cel/io.go
  vendor/github.com/google/cel-go/cel/optimizer.go
  vendor/github.com/google/cel-go/cel/program.go
  vendor/github.com/google/cel-go/checker/checker.go
  vendor/github.com/google/cel-go/common/decls/decls.go
  vendor/github.com/google/cel-go/common/errors.go
  vendor/github.com/google/cel-go/ext/BUILD.bazel
  vendor/github.com/google/cel-go/interpreter/planner.go
  vendor/github.com/google/cel-go/parser/macro.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/procfs/.golangci.yml
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/fs.go
  vendor/github.com/prometheus/procfs/fs_statfs_notype.go
  vendor/github.com/prometheus/procfs/fscache.go
  vendor/github.com/prometheus/procfs/internal/fs/fs.go
  vendor/github.com/prometheus/procfs/internal/util/parse.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_dev_snmp6.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_tcp.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_io.go
  vendor/github.com/prometheus/procfs/proc_smaps.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/modules.txt
Labels: kind/cleanup, priority/important-longterm, area/dependency, lgtm, size/XL, approved

#87 [0.5] Bump dependencies and builder to `golang-1.24`
  go.mod
  go.sum
  images/local-csi-driver-tests/Dockerfile
  images/local-csi-driver/Dockerfile
  vendor/cel.dev/expr/README.md
  vendor/github.com/go-openapi/jsonpointer/.golangci.yml
  vendor/github.com/go-openapi/jsonpointer/errors.go
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/errors.go
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/yaml.go
  vendor/github.com/google/cel-go/cel/env.go
  vendor/github.com/google/cel-go/cel/inlining.go
  vendor/github.com/google/cel-go/cel/io.go
  vendor/github.com/google/cel-go/cel/optimizer.go
  vendor/github.com/google/cel-go/cel/program.go
  vendor/github.com/google/cel-go/checker/checker.go
  vendor/github.com/google/cel-go/common/decls/decls.go
  vendor/github.com/google/cel-go/common/errors.go
  vendor/github.com/google/cel-go/ext/BUILD.bazel
  vendor/github.com/google/cel-go/interpreter/planner.go
  vendor/github.com/google/cel-go/parser/macro.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/procfs/.golangci.yml
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/fs.go
  vendor/github.com/prometheus/procfs/fs_statfs_notype.go
  vendor/github.com/prometheus/procfs/fscache.go
  vendor/github.com/prometheus/procfs/internal/fs/fs.go
  vendor/github.com/prometheus/procfs/internal/util/parse.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_dev_snmp6.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_tcp.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_io.go
  vendor/github.com/prometheus/procfs/proc_smaps.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/modules.txt
Labels: kind/cleanup, priority/important-soon, area/dependency, lgtm, size/XL, approved

#89 Use the release GitHub Action from operator `master`
  .github/workflows/releases.yaml
Labels: kind/cleanup, priority/important-soon, size/XS, lgtm, approved

#90 [v0.5] Use the release GitHub Action from operator `master`
  .github/workflows/releases.yaml
Labels: kind/cleanup, priority/important-soon, size/XS, lgtm, approved
